## 1. Introduction
<p><img src="https://assets.datacamp.com/production/project_1197/img/google_play_store.png" alt="Google Play logo"></p>
<p>Mobile apps are everywhere. They are easy to create and can be very lucrative from the business standpoint. Specifically, Android is expanding as an operating system and has captured more than 74% of the total market<sup><a href="https://www.statista.com/statistics/272698/global-market-share-held-by-mobile-operating-systems-since-2009">[1]</a></sup>. </p>
<p>The Google Play Store apps data has enormous potential to facilitate data-driven decisions and insights for businesses. In this notebook, we will analyze the Android app market by comparing ~10k apps in Google Play across different categories. We will also use the user reviews to draw a qualitative comparision between the apps.</p>
<p>The dataset you will use here was scraped from Google Play Store in September 2018 and was published on <a href="https://www.kaggle.com/lava18/google-play-store-apps">Kaggle</a>. Here are the details: <br>
<br></p>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/apps.csv</b></div>
This file contains all the details of the apps on Google Play. There are 9 features that describe a given app.
<ul>
    <li><b>App:</b> Name of the app</li>
    <li><b>Category:</b> Category of the app. Some examples are: ART_AND_DESIGN, FINANCE, COMICS, BEAUTY etc.</li>
    <li><b>Rating:</b> The current average rating (out of 5) of the app on Google Play</li>
    <li><b>Reviews:</b> Number of user reviews given on the app</li>
    <li><b>Size:</b> Size of the app in MB (megabytes)</li>
    <li><b>Installs:</b> Number of times the app was downloaded from Google Play</li>
    <li><b>Type:</b> Whether the app is paid or free</li>
    <li><b>Price:</b> Price of the app in US$</li>
    <li><b>Last Updated:</b> Date on which the app was last updated on Google Play </li>

</ul>
</div>
<div style="background-color: #efebe4; color: #05192d; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/user_reviews.csv</b></div>
This file contains a random sample of 100 <i>[most helpful first](https://www.androidpolice.com/2019/01/21/google-play-stores-redesigned-ratings-and-reviews-section-lets-you-easily-filter-by-star-rating/)</i> user reviews for each app. The text in each review has been pre-processed and passed through a sentiment analyzer.
<ul>
    <li><b>App:</b> Name of the app on which the user review was provided. Matches the `App` column of the `apps.csv` file</li>
    <li><b>Review:</b> The pre-processed user review text</li>
    <li><b>Sentiment Category:</b> Sentiment category of the user review - Positive, Negative or Neutral</li>
    <li><b>Sentiment Score:</b> Sentiment score of the user review. It lies between [-1,1]. A higher score denotes a more positive sentiment.</li>

</ul>
</div>
<p>From here on, it will be your task to explore and manipulate the data until you are able to answer the three questions described in the instructions panel.<br></p>

In [92]:
# Use this cell to begin your analysis, and add as many as you would like!
import pandas as pd

In [93]:
apps=pd.read_csv("datasets/apps.csv")
apps.info()
apps.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
App             9659 non-null object
Category        9659 non-null object
Rating          8196 non-null float64
Reviews         9659 non-null int64
Size            8432 non-null float64
Installs        9659 non-null object
Type            9659 non-null object
Price           9659 non-null float64
Last Updated    9659 non-null object
dtypes: float64(3), int64(1), object(5)
memory usage: 679.2+ KB

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0.0,"June 20, 2018"

In [94]:
char_to_remove=[',','+']

In [95]:
for char in char_to_remove:
    apps['Installs']=apps['Installs'].apply(lambda x: x.replace(char, ''))
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,"January 7, 2018"
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,"January 15, 2018"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,"August 1, 2018"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,"June 8, 2018"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,"June 20, 2018"

In [96]:
apps['Installs']=apps['Installs'].astype(int)
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9659 entries, 0 to 9658
Data columns (total 9 columns):
App             9659 non-null object
Category        9659 non-null object
Rating          8196 non-null float64
Reviews         9659 non-null int64
Size            8432 non-null float64
Installs        9659 non-null int64
Type            9659 non-null object
Price           9659 non-null float64
Last Updated    9659 non-null object
dtypes: float64(3), int64(2), object(4)
memory usage: 679.2+ KB

In [113]:
app_category_info = apps.groupby(by=['Category']).agg({'App':'count', 'Price':'mean', 'Rating':'mean'})
app_category_info

                      App     Price    Rating
Category
ART_AND_DESIGN         64  0.093281  4.357377
AUTO_AND_VEHICLES      85  0.158471  4.190411
BEAUTY                 53  0.000000  4.278571
BOOKS_AND_REFERENCE   222  0.539505  4.344970
BUSINESS              420  0.417357  4.098479
COMICS                 56  0.000000  4.181481
COMMUNICATION         315  0.263937  4.121484
DATING                171  0.160468  3.970149
EDUCATION             119  0.150924  4.364407
ENTERTAINMENT         102  0.078235  4.135294
EVENTS                 64  1.718594  4.435556
FAMILY               1832  1.309967  4.179664
FINANCE               345  8.408203  4.115563
FOOD_AND_DRINK        112  0.075714  4.172340
GAME                  959  0.296465  4.247368
HEALTH_AND_FITNESS    288  0.223438  4.243033
HOUSE_AND_HOME         74  0.000000  4.150000
LIBRARIES_AND_DEMO     84  0.011786  4.178125
LIFESTYLE             369  6.398022  4.093355
MAPS_AND_NAVIGATION   131  0.205725  4.036441
MEDICAL               395  2.520759  4.166552
NEWS_AND_MAGAZINES    254  0.015669  4.121569
PARENTING              60  0.159667  4.300000
PERSONALIZATION       376  0.400213  4.332215
PHOTOGRAPHY           281  0.420925  4.157414
PRODUCTIVITY          374  0.670936  4.183389
SHOPPING              202  0.027129  4.230000
SOCIAL                239  0.066820  4.247291
SPORTS                325  0.307692  4.216154
TOOLS                 827  0.323156  4.039554
TRAVEL_AND_LOCAL      219  0.228082  4.069519
VIDEO_PLAYERS         163  0.064172  4.044595
WEATHER                79  0.410380  4.243056

In [114]:
app_category_info = app_category_info.rename(columns={'App':'Number of apps', 'Price':'Average price', 'Rating':'Average rating'})

In [115]:
app_category_info.head()

                     Number of apps  Average price  Average rating
Category
ART_AND_DESIGN                   64       0.093281        4.357377
AUTO_AND_VEHICLES                85       0.158471        4.190411
BEAUTY                           53       0.000000        4.278571
BOOKS_AND_REFERENCE             222       0.539505        4.344970
BUSINESS                        420       0.417357        4.098479

In [100]:
reviews= pd.read_csv('datasets/user_reviews.csv')
reviews

,App,Review,Sentiment Category,Sentiment Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.000000
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.250000
2,10 Best Foods for You,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.400000
4,10 Best Foods for You,Best idea us,Positive,1.000000
5,10 Best Foods for You,Best way,Positive,1.000000
6,10 Best Foods for You,Amazing,Positive,0.600000
7,10 Best Foods for You,NaN,NaN,NaN
8,10 Best Foods for You,"Looking forward app,",Neutral,0.000000
9,10 Best Foods for You,It helpful site ! It help foods get !,Neutral,0.000000
10,10 Best Foods for You,good you.,Positive,0.700000
11,10 Best Foods for You,Useful information The amount spelling errors ...,Positive,0.200000
12,10 Best Foods for You,"Thank you! Great app!! Add arthritis, eyes, im...",Positive,0.750000
13,10 Best Foods for You,Greatest ever Completely awesome maintain heal...,Positive,0.992188
14,10 Best Foods for You,Good health...... Good health first priority.....,Positive,0.550000
15,10 Best Foods for You,NaN,NaN,NaN
16,10 Best Foods for You,Health It's important world either life . thin...,Positive,0.450000
17,10 Best Foods for You,"Mrs sunita bhati I thankful developers,to make...",Positive,0.600000
18,10 Best Foods for You,Very Useful in diabetes age 30. I need control...,Positive,0.295000
19,10 Best Foods for You,One greatest apps.,Positive,1.000000
20,10 Best Foods for You,good nice,Positive,0.650000
21,10 Best Foods for You,Healthy Really helped,Positive,0.350000
22,10 Best Foods for You,God health,Neutral,0.000000
23,10 Best Foods for You,HEALTH SHOULD ALWAYS BE TOP PRIORITY. !!. ON M...,Positive,0.781250
24,10 Best Foods for You,An excellent A useful,Positive,0.650000
25,10 Best Foods for You,I found lot wealth form health...,Neutral,0.000000
26,10 Best Foods for You,Because I found important.,Positive,0.400000
27,10 Best Foods for You,Healthy Eating,Positive,0.500000
28,10 Best Foods for You,Very good Simply good,Positive,0.805000
29,10 Best Foods for You,On test....,Neutral,0.000000
...,...,...,...,...
64265,Houzz Interior Design Ideas,NaN,NaN,NaN
64266,Houzz Interior Design Ideas,NaN,NaN,NaN
64267,Houzz Interior Design Ideas,NaN,NaN,NaN
64268,Houzz Interior Design Ideas,NaN,NaN,NaN
64269,Houzz Interior Design Ideas,NaN,NaN,NaN
64270,Houzz Interior Design Ideas,NaN,NaN,NaN
64271,Houzz Interior Design Ideas,NaN,NaN,NaN
64272,Houzz Interior Design Ideas,NaN,NaN,NaN
64273,Houzz Interior Design Ideas,NaN,NaN,NaN
64274,Houzz Interior Design Ideas,NaN,NaN,NaN
64275,Houzz Interior Design Ideas,NaN,NaN,NaN
64276,Houzz Interior Design Ideas,NaN,NaN,NaN
64277,Houzz Interior Design Ideas,NaN,NaN,NaN
64278,Houzz Interior Design Ideas,NaN,NaN,NaN
64279,Houzz Interior Design Ideas,NaN,NaN,NaN
64280,Houzz Interior Design Ideas,NaN,NaN,NaN
64281,Houzz Interior Design Ideas,NaN,NaN,NaN
64282,Houzz Interior Design Ideas,NaN,NaN,NaN
64283,Houzz Interior Design Ideas,NaN,NaN,NaN
64284,Houzz Interior Design Ideas,NaN,NaN,NaN
64285,Houzz Interior Design Ideas,NaN,NaN,NaN
64286,Houzz Interior Design Ideas,NaN,NaN,NaN
64287,Houzz Interior Design Ideas,NaN,NaN,NaN
64288,Houzz Interior Design Ideas,NaN,NaN,NaN
64289,Houzz Interior Design Ideas,NaN,NaN,NaN
64290,Houzz Interior Design Ideas,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN

In [101]:
finance_apps = apps[apps['Category']=='FINANCE']
finance_apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
837,K PLUS,FINANCE,4.4,124424,NaN,10000000,Free,0.0,"June 26, 2018"
838,ING Banking,FINANCE,4.4,39041,NaN,1000000,Free,0.0,"August 3, 2018"
839,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018"
840,The postal bank,FINANCE,3.7,36718,NaN,5000000,Free,0.0,"July 16, 2018"
841,KTB Netbank,FINANCE,3.8,42644,19.0,5000000,Free,0.0,"June 28, 2018"

In [102]:
free_finance_apps = finance_apps[finance_apps['Type']=='Free']
free_finance_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated
837,K PLUS,FINANCE,4.4,124424,NaN,10000000,Free,0.0,"June 26, 2018"
838,ING Banking,FINANCE,4.4,39041,NaN,1000000,Free,0.0,"August 3, 2018"
839,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018"
840,The postal bank,FINANCE,3.7,36718,NaN,5000000,Free,0.0,"July 16, 2018"
841,KTB Netbank,FINANCE,3.8,42644,19.0,5000000,Free,0.0,"June 28, 2018"
842,Mobile Bancomer,FINANCE,4.2,278082,70.0,10000000,Free,0.0,"July 30, 2018"
843,Nedbank Money,FINANCE,4.2,6076,32.0,500000,Free,0.0,"July 28, 2018"
844,SCB EASY,FINANCE,4.2,112656,93.0,5000000,Free,0.0,"July 19, 2018"
845,CASHIER,FINANCE,3.3,335738,NaN,10000000,Free,0.0,"May 3, 2018"
846,Rabo Banking,FINANCE,3.4,31906,NaN,1000000,Free,0.0,"July 19, 2018"
847,Capitec Remote Banking,FINANCE,4.3,20672,NaN,1000000,Free,0.0,"May 8, 2018"
848,Itau bank,FINANCE,4.2,957973,40.0,10000000,Free,0.0,"July 30, 2018"
849,Nubank,FINANCE,4.7,130582,24.0,5000000,Free,0.0,"August 2, 2018"
850,The Societe Generale App,FINANCE,4.1,31218,NaN,1000000,Free,0.0,"July 31, 2018"
851,IKO,FINANCE,4.7,167168,20.0,1000000,Free,0.0,"July 4, 2018"
852,Cash App,FINANCE,4.0,34428,15.0,10000000,Free,0.0,"August 2, 2018"
853,Standard Bank / Stanbic Bank,FINANCE,3.6,15247,28.0,1000000,Free,0.0,"July 13, 2018"
854,Bualuang mBanking,FINANCE,4.0,48445,10.0,5000000,Free,0.0,"July 16, 2018"
855,Intesa Sanpaolo Mobile,FINANCE,3.6,35518,NaN,1000000,Free,0.0,"July 2, 2018"
856,UBA Mobile Banking,FINANCE,4.3,12185,NaN,1000000,Free,0.0,"June 8, 2018"
857,BBVA Spain,FINANCE,4.2,36746,NaN,5000000,Free,0.0,"July 24, 2018"
858,MyMo by GSB,FINANCE,4.2,21996,14.0,1000000,Free,0.0,"July 19, 2018"
859,VTB-Online,FINANCE,4.1,138371,NaN,5000000,Free,0.0,"August 2, 2018"
860,Ecobank Mobile Banking,FINANCE,4.0,12073,42.0,1000000,Free,0.0,"May 25, 2018"
861,Banorte Movil,FINANCE,4.1,111632,65.0,1000000,Free,0.0,"June 9, 2018"
862,Wells Fargo Mobile,FINANCE,4.4,250706,37.0,10000000,Free,0.0,"July 31, 2018"
863,Credit Karma,FINANCE,4.7,706301,NaN,10000000,Free,0.0,"July 31, 2018"
864,BZWBK24 mobile,FINANCE,4.5,64959,39.0,1000000,Free,0.0,"June 18, 2018"
865,PayPal,FINANCE,4.3,659741,47.0,50000000,Free,0.0,"July 18, 2018"
866,Capital One® Mobile,FINANCE,4.6,510392,79.0,10000000,Free,0.0,"August 1, 2018"
...,...,...,...,...,...,...,...,...,...
9117,FD Community FCU Mobile,FINANCE,4.7,175,12.0,1000,Free,0.0,"June 12, 2018"
9122,Policy And FD Manager,FINANCE,4.3,20,4.8,500,Free,0.0,"June 9, 2018"
9127,FD Calculator | Term Deposit | Fixed Deposit,FINANCE,4.8,12,2.7,1000,Free,0.0,"June 13, 2018"
9129,Financial Calculator India,FINANCE,4.6,13819,3.9,1000000,Free,0.0,"July 4, 2018"
9130,"FD Calculator (EMI, SIP, RD & Loan Eligilibility)",FINANCE,5.0,104,2.3,1000,Free,0.0,"August 7, 2018"
9132,"EMI, FD, RD - Bank Calculator",FINANCE,4.7,42,3.5,5000,Free,0.0,"April 2, 2017"
9134,RD/FD Calculator,FINANCE,4.4,92,1.5,10000,Free,0.0,"January 31, 2017"
9137,Fix Deposit Calculator (FD),FINANCE,4.1,7,2.1,1000,Free,0.0,"February 6, 2018"
9138,FD Interest Calculator,FINANCE,4.2,17,4.7,5000,Free,0.0,"January 18, 2015"
9139,Deposit Calculator FD & RD,FINANCE,4.4,18,3.4,10000,Free,0.0,"January 21, 2017"
9141,Banking Calculator,FINANCE,4.5,3704,4.6,100000,Free,0.0,"March 20, 2018"
9144,EMI/FD/RD/PV/IRR/BEP/EOQ Calc,FINANCE,4.5,58,2.7,10000,Free,0.0,"December 9, 2015"
9145,EMI Calculator | FD Calculator | RD calculator,FINANCE,4.6,106,4.4,10000,Free,0.0,"March 19, 2018"
9149,Santa Fe FCU Mobile Banking,FINANCE,4.3,12,9.0,1000,Free,0.0,"January 22, 2018"
9152,FE CREDIT - TET VUI,FINANCE,4.1,125,15.0,50000,Free,0.0,"March 6, 2018"
9159,Caprock Santa Fe Credit Union,FINANCE,NaN,0,2.9,100,Free,0.0,"March 23, 2018"
9169,FE CPS,FINANCE,3.0,62,17.0,10000,Free,0.0,"June 26, 2017"
9189,FG Wallet,FINANCE,NaN,9,12.0,1000,Free,0.0,"June 6, 2018"
9245,FH Wallet,FINANCE,NaN,0,9.9,1,Free,0.0,"July 26, 2018"
9252,First Hawaiian Bank Mobile,FINANCE,2.1,232,29.0,10000,Free,0.0,"May 9, 2018"
9295,FI CFL,FINANCE,3.7,112,3.9,10000,Free,0.0,"July 5, 2018"
9453,PriorityONE Credit Union of Fl,FINANCE,4.7,178,12.0,1000,Free,0.0,"June 12, 2018"
9468,First Federal Bank of Florida,FINANCE,4.3,133,30.0,10000,Free,0.0,"May 23, 2018"
9488,SB · FN 1870 Mobile Banking,FINANCE,2.9,139,3.3,10000,Free,0.0,"June 19, 2017"
9522,FO BOULANGER,FINANCE,NaN,10,19.0,50,Free,0.0,"May 15, 2018"
9540,BankNordik,FINANCE,3.9,28,15.0,5000,Free,0.0,"August 8, 2018"
9564,FP Markets,FINANCE,NaN,1,2.0,100,Free,0.0,"January 30, 2018"
9565,FP Boss,FINANCE,NaN,1,5.8,1,Free,0.0,"July 27, 2018"
9572,FP FCU,FINANCE,3.6,48,26.0,5000,Free,0.0,"April 5, 2018"
9636,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5,10000,Free,0.0,"May 19, 2016"

In [103]:
merged_df = pd.merge(free_finance_apps,reviews, on='App')
merged_df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Last Updated,Review,Sentiment Category,Sentiment Score
0,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018","Forget paying app, designed make fail payments...",Negative,-0.500000
1,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018","It's working expected, talking best bank Mexic...",Positive,0.400000
2,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018",It has many problems with Android 8.1. You can...,Positive,0.250000
3,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018","I changed my phone to a Xiaomi Redmi Note 5, t...",Positive,0.175000
4,Citibanamex Movil,FINANCE,3.6,52306,42.0,5000000,Free,0.0,"July 27, 2018",In her eagerness to make her look pretty with ...,Negative,-0.158333

In [104]:
app_sentiment_score=merged_df.groupby('App').agg({'Sentiment Score':'mean'})
app_sentiment_score.head()

                                Sentiment Score
App
A+ Mobile                              0.329592
ACE Elite                              0.252171
Acorns - Invest Spare Change           0.046667
Amex Mobile                            0.175666
Associated Credit Union Mobile         0.388093

In [105]:
app_sentiment_score=app_sentiment_score.sort_values('Sentiment Score',ascending=False)

In [116]:
top_10_user_feedback=app_sentiment_score[:10]
top_10_user_feedback

                                            Sentiment Score
App
BBVA Spain                                         0.515086
Associated Credit Union Mobile                     0.388093
BankMobile Vibe App                                0.353455
A+ Mobile                                          0.329592
Current debit card and app made for teens          0.327258
BZWBK24 mobile                                     0.326883
Even - organize your money, get paid early         0.283929
Credit Karma                                       0.270052
Fortune City - A Finance App                       0.266966
Branch                                             0.264230